server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        registration:
          spring:
            provider: "spring"
            client-id: "spring"
            client-secret: "spring"
            authorization-grant-type: "authorization_code"
            client-authentication-method: "client_secret_basic"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: "openid"