server:
  port: 8080
spring:
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              redirect-uris:
                - "http://localhost:8081/login/oauth2/code/spring"