spring:
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              redirect-uris:
                - "http://localhost:8080/login/oauth2/code/spring"