spring:
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: "http://127.0.0.1:9090"
        registration:
          spring:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"