spring:
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              redirect-uris:
                - "http://127.0.0.1:8081/login/oauth2/code/spring"