spring:
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: "http://localhost:9090"
        registration:
          spring:
            redirect-uri: "http://localhost:8081/login/oauth2/code/{registrationId}"